config/routes.rb
Namelist::Application.routes.draw do
  resources :tops

end

app/models/top.rb
class Top < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  # GET /tops
  # GET /tops.json
  def index
    @tops = Top.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tops }
    end
  end

  # GET /tops/1
  # GET /tops/1.json
  def show
    @top = Top.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @top }
    end
  end

  # GET /tops/new
  # GET /tops/new.json
  def new
    @top = Top.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @top }
    end
  end

  # GET /tops/1/edit
  def edit
    @top = Top.find(params[:id])
  end

  # POST /tops
  # POST /tops.json
  def create
    @top = Top.new(params[:top])

    respond_to do |format|
      if @top.save
        format.html { redirect_to @top, notice: 'Top was successfully created.' }
        format.json { render json: @top, status: :created, location: @top }
      else
        format.html { render action: "new" }
        format.json { render json: @top.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tops/1
  # PUT /tops/1.json
  def update
    @top = Top.find(params[:id])

    respond_to do |format|
      if @top.update_attributes(params[:top])
        format.html { redirect_to @top, notice: 'Top was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @top.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tops/1
  # DELETE /tops/1.json
  def destroy
    @top = Top.find(params[:id])
    @top.destroy

    respond_to do |format|
      format.html { redirect_to tops_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/to_ps_helper.rb
module ToPsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Namelist</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tops/_form.html.erb
<%= form_for(@top) do |f| %>
  <% if @top.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@top.errors.count, "error") %> prohibited this top from being saved:</h2>

      <ul>
      <% @top.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tops/edit.html.erb
<h1>Editing top</h1>

<%= render 'form' %>

<%= link_to 'Show', @top %> |
<%= link_to 'Back', tops_path %>

app/views/tops/index.html.erb
<h1>Listing tops</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tops.each do |top| %>
  <tr>
    <td><%= top.name %></td>
    <td><%= link_to 'Show', top %></td>
    <td><%= link_to 'Edit', edit_top_path(top) %></td>
    <td><%= link_to 'Destroy', top, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Top', new_top_path %>

app/views/tops/new.html.erb
<h1>New top</h1>

<%= render 'form' %>

<%= link_to 'Back', tops_path %>

app/views/tops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @top.name %>
</p>


<%= link_to 'Edit', edit_top_path(@top) %> |
<%= link_to 'Back', tops_path %>